language: node_js
node_js:
    - '12'

services:
    - mongodb

install:
    - npm install
    - npm install --prefix client
    - npm install --prefix server

script:
    - npm run test

cache:
    directories:
        - 'node_modules'
